//
// Created by USER on 4/14/2017.
//

#ifndef MULTIFOCUSIMAGE_FOCUS_DEPTH_ESTIMATION_H
#define MULTIFOCUSIMAGE_FOCUS_DEPTH_ESTIMATION_H


class focus_depth_estimation {

};


#endif //MULTIFOCUSIMAGE_FOCUS_DEPTH_ESTIMATION_H
